action_dim: 3
batch_size: 8
config: conf/immi_learn_pose_baseline.yaml
embed_dim: 128
epochs: 100
freeze_till: 20
gamma: 0.9
lr: 0.001
num_heads: 4
num_workers: 4
period: 3
pretrained: exp/metric_learn/checkpoints/last.ckpt
resume: null
train_csv: train.csv
val_csv: val.csv
